### driver names config file ###
/**:
  ros__parameters:
    driver_names: ["player1"]
    # driver_names: ["player1", "player2"]
/multiagent_control_node:
  ros__parameters:
    full_lock_left: [0.225]
    full_lock_right: [-0.225]
    # full_lock_left: [0.225, 0.225]
    # full_lock_right: [-0.225, -0.225]
/gamepad_multiplexer_node:
  ros__parameters:
    frequency: 100.0