string filename
string frame_id
nav_msgs/Path new_raceline
---
string message
int16 error_code
int16 SUCCESS=1
int16 UNKNOWN_ERROR=0
int16 BOTH_ARGUMENTS_SET=-1
int16 NEITHER_ARGUMENT_SET=-2
int16 FILEPATH_NOT_FOUND=-3
int16 INVALID_QUATERNION=-4
int16 SELF_INTERSECTING_PATH=-5
int16 TF_FAILURE=-6